config/routes.rb
Phy::Application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#main'

  get '/profile' => 'users#profile'

  get '/search_applicant' => 'advisers#search_applicant'
  post '/add_applicant' => 'advisers#add_applicant'
  delete '/adviser/applicants/:applicant_id' => 'advisers#remove_advisership', as: 'remove_advisership'
  get '/adviser/applicants/:applicant_id' => 'advisers#show_applicant', as: 'show_applicant'
 	post '/adviser/applicants/:applicant_id/update_status' => 'advisers#update_status', as: 'update_status'
 	post '/adviser/applicants/:applicant_id/task_status/:task_status_id/update_status' => 'advisers#update_task_status', as: 'update_task_status'
 	post '/adviser/applicants/:applicant_id/create_exam_answer' => 'advisers#create_exam_answer', as: 'create_exam_answer'	
 	delete '/adviser/applicants/:applicant_id/exam_answers/:exam_answer_id' => 'advisers#delete_exam_answer', as: 'delete_exam_answer'
 	post '/adviser/applicants/:applicant_id/update_message' => 'advisers#update_message', as: 'update_message'

 	get '/applicant/exams/:exam_answer_id' => 'applicants#show_exam', as: 'show_exam'
 	post '/applicant/:exam_answer_id' => 'applicants#submit_answer', as: 'submit_answer'
 	get '/adviser/applicants/:applicant_id/exams/:exam_answer_id' => 'advisers#detail_about_exam', as: 'detail_exam'
end

app/controllers/advisers_controller.rb
class AdvisersController < ApplicationController
	before_action :authenticate_user!
	
	def search_applicant
		@applicant = User.where(user_code: params[:user_code], user_type: 0).first
		render layout: false
	end

	def add_applicant
		applicant = User.where(user_code: params[:user_code]).first
		if applicant
			applicant.update_attributes adviser: current_user
			redirect_to profile_path, flash: { success: "متقاضی با موفقیت اضافه شد!"}
		else
			redirect_to profile_path, flash: { error: "متقاضی یافت نشد!" }
		end
	end

	def remove_advisership
		puts params
		applicant = current_user.applicants.where(id: params[:applicant_id]).first
		if applicant
			applicant.update_attributes adviser_id: nil
			redirect_to profile_path, flash: { success: 'مسئولیت با موفقیت حذف شد!' }
		else
			redirect_to profile_path, flash: { error: 'متقاضی یافت نشد!' }
		end
	end

	def show_applicant
		@applicant = current_user.applicants.where(id: params[:applicant_id]).first
		return redirect_to profile_path, flash: { error: 'متقاضی یافت نشد!' } unless @applicant
	end

	def update_status
		applicant = current_user.applicants.where(id: params[:applicant_id]).first
		return redirect_to profile_path, flash: { error: 'متقاضی یافت نشد!' } unless applicant
		if applicant.update_attributes status: params[:status][:status]
			redirect_to show_applicant_path(applicant), flash: { success: 'وضعیت کلی متقاضی به روز شد' }
		else
			redirect_to show_applicant_path(applicant), flash: { error: 'خطا.' }
		end
	end

	def update_task_status
		applicant = current_user.applicants.where(id: params[:applicant_id]).first
		return redirect_to profile_path, flash: { error: 'متقاضی یافت نشد!' } unless applicant
		task_status = applicant.task_statuses.where(id: params[:task_status_id]).first
		return redirect_to profile_path, flash: { error: 'تسک یافت نشد!' } unless task_status
		if task_status.value
			unless task_status.update_attributes value: false
				return redirect_to show_applicant_path(applicant), flash: { error: 'خطا.' }
			end
		else
			unless task_status.update_attributes value: true
				return redirect_to show_applicant_path(applicant), flash: { error: 'خطا.' }
			end
		end
		return redirect_to show_applicant_path(applicant)
	end

	def create_exam_answer
		applicant = current_user.applicants.where(id: params[:applicant_id]).first
		return redirect_to profile_path, flash: { error: 'متقاضی یافت نشد!' } unless applicant
		exam = Exam.where(name: params[:exam][:name]).first
		if exam.exam_answers.where(user_id: applicant.id).first
			return redirect_to profile_path, flash: { error: 'آزمون اضافه شده است!' }
		end
		exam.exam_answers.create! user_id: applicant.id
		redirect_to show_applicant_path(applicant), flash: { success: 'آزمون با موفقیت اضافه شد' }
	end

	def delete_exam_answer
		applicant = current_user.applicants.where(id: params[:applicant_id]).first
		return redirect_to profile_path, flash: { error: 'متقاضی یافت نشد!' } unless applicant
		exam_answer = applicant.exam_answers.where(id: params[:exam_answer_id]).first
		return redirect_to profile_path, flash: { error: 'آزمون یافت نشد!' } unless exam_answer
		exam_answer.destroy
		redirect_to show_applicant_path(applicant), flash: { success: 'آزمون با موفقیت حذف شد' }
	end

	def update_message
		applicant = current_user.applicants.where(id: params[:applicant_id]).first
		return redirect_to profile_path, flash: { error: 'متقاضی یافت نشد!' } unless applicant
		applicant.update_attributes! adviser_message: params[:message][:content]
		redirect_to show_applicant_path(applicant), flash: { success: 'وضعیت متقاضی به روز شد.' }
	end

	def detail_about_exam
		applicant = current_user.applicants.where(id: params[:applicant_id]).first
		return redirect_to profile_path, flash: { error: 'متقاضی یافت نشد!' } unless applicant
		@exam_answer = applicant.exam_answers.where(id: params[:exam_answer_id]).first
		return redirect_to profile_path, flash: { error: 'آزمون یافت نشد!' } unless @exam_answer
	end


end

app/helpers/advisers_helper.rb
module AdvisersHelper
end

app/views/advisers/_adviser_message.html.erb
<p>
	وضعیت کاربر، که به صورت پیغام به او نمایش داده می‌شود.
</p>
<p>
	<span class="label label-info">
	<%= applicant.adviser_message %>
	</span>
</p>

<p>
	در صورت نیاز تغییر دهید:
</p>
<p>
  <%= simple_form_for :message, url: update_message_path(applicant), html: {class: 'form-horizontal', role: 'form'} do |f| %>
  <%= f.input :content, input_html: {class: 'form-control col-md-8'}, label: false %>
  <%= f.button :submit, 'به روز کن',class: 'btn btn-primary' %>
  <% end %>
</p>

app/views/advisers/_adviser_profile.html.erb
<%= render partial: 'normal_profile_div' %>

<div class="tabbable tabs-left">
	<ul class="nav nav-tabs">
		<% class1 = "" %>
		<% class1 = 'active' if params[:tab] == 'tab1' %>
		<% class2 = "" %>
		<% class2 = 'active' if params[:tab] == 'tab9' %>
		<% class1 = 'active' if (class1 == "" and class2 == "") %>

		<li class="<%= class1 %>"><a href="#tab1" data-toggle="tab">لیست متقاضیان تحت نظر</a></li>
		<li class="<%= class2 %>"> <a href="#tab9" data-toggle="tab">اضافه کردن متقاضی</a></li>
	</ul>

	<div class="tab-content">
		<div class="<%= if (params[:tab] == 'tab1' || !params[:tab])then 'tab-pane active'  else 'tab-pane' end%>" id="tab1">
			<%= render partial: 'advisers/applicant_list' %>
		</div>
		<div class="<%= if params[:tab] == 'tab9' then 'tab-pane active'  else 'tab-pane' end%>" id="tab9">
			<%= render partial: 'advisers/search' %>
		</div>
	</div>
</div>

app/views/advisers/_applicant_information_for_customer.html.erb
<div class="well well-sm">
  <div class="media">
    <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="col-xs-12 col-sm-4 center-block img-circle img-responsive">
    <div class="media-body">
      <h4 class="media-heading"><%= full_name applicant %></h4>
      <p><span class="label label-primary"><%= role_label applicant %> </span></p>
      <p>
        کد کاربری
        <span class="label label-success"><%= applicant.user_code %> </span>
      </p>
      <p>
        نام کاربری
        <strong><%= applicant.username %> </strong>
      </p>
      <p>
        پست الکترونیکی
        <strong><%= applicant.email %> </strong>
      </p>
      <p>
        سن
        <strong><%= applicant.age %> </strong>
      </p>
    </div>
  </div>
</div>

app/views/advisers/_applicant_list.html.erb
<div class="table-responsive">
  <table class="table table-condensed table-striped  table-hover no-margin borderless">
    <thead>
      <tr>
        <th style="width:10%" class="text-center hidden-phone">تصویر</th>
        <th style="width:20%" class="text-center hidden-phone">نام متقاضی</th>
        <th style="width:10%" class="text-center hidden-phone">پست الکترونیکی</th>
        <th style="width:15%" class="text-center hidden-phone">نام کاربری</th>
        <th style="width:10%" class="text-center hidden-phone">کد کاربری</th>
        <th style="width:15%" class="text-center hidden-phone">عملیات</th>
      </tr>
    </thead>
    <tbody>
      <% current_user.applicants.each do |applicant| %>
        <%= render partial: 'advisers/single_applicant', locals: { applicant: applicant } %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/advisers/_applicant_profile.html.erb
I'm a applicant!

app/views/advisers/_exams_list.html.erb
<% if applicant.exam_answers.any? %>
<div class="table-responsive">
  <table class="table table-condensed table-striped  table-hover no-margin borderless">
    <thead>
      <tr>
        <th style="width:30%" class="text-center hidden-phone">وضعیت</th>
        <th style="width:20%" class="text-center hidden-phone">نام آزمون</th>
        <th style="width:20%" class="text-center hidden-phone">نتیجه</th>
        <th style="width:20%" class="text-center hidden-phone">عملیات</th>
      </tr>
    </thead>
    <tbody>
      <% applicant.exam_answers.each do |answer| %>
      <tr>
        <td class="text-center">
          <% if answer.status %>
          <span class="label label-success"> داده </span>
          <% else %>
          <span class="label label-danger"> نداده </span>
          <% end %>
        </td>
        <td class="text-center">
          <%= answer.exam.name %>
        </td>
        <td class="text-center">
          <% if answer.score %>
          <%= answer.score %> |‌ <%= link_to 'مشاهده جزئیات', detail_exam_path(applicant, answer) %>
          <% end %>
        </td>
        <td class="text-center">
          <%= link_to 'حذف', delete_exam_answer_path(applicant,answer), method: :delete, class: 'btn btn-danger' %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
در حال حاضر آزمونی ندارد.
<% end %>

<% unrolled_exams = applicant.get_unrolled_exams.map { |content| [content,content] } %>
<% if unrolled_exams.any? %>
<p>
  <%= simple_form_for :exam, url: create_exam_answer_path(applicant), html: {class: 'form-horizontal', role: 'form'} do |f| %>
  <%= f.input :name, collection: unrolled_exams, selected: (0), input_html: {class: 'form-control col-md-8'}, label: false %>
  <%= f.button :submit, 'اضافه کن',class: 'btn btn-primary' %>
  <% end %>
  <% end %>
</p>

app/views/advisers/_search.html.erb
<form class="form-horizontal" id="live-search-form" method="get" action="<%= search_applicant_path %>">
    <div class="form-group">
      <label for="inputType" class="col-md-2 control-label">کد متقاضی</label>
      <div class="col-md-3">
          <input type="text" class="form-control" name="user_code" id="big-search-box">
      </div>
    </div>
</form>

<div id="live-search-results"></div>

<script type='text/javascript'>
	$("#big-search-box").bind("keyup", function() {
  $("#big-search-box").addClass("loading"); // show the spinner
  var form = $("#live-search-form"); // grab the form wrapping the search bar.

  var url = "/search_applicant"; // live_search action.   
  var formData = form.serialize(); // grab the data in the form   
  $.get(url, formData, function(html) { // perform an AJAX get

    $("#big-search-box").removeClass("loading"); // hide the spinner

    $("#live-search-results").html(html); // replace the "results" div with the results

});

});
</script>

app/views/advisers/_single_applicant.html.erb
<tr>
  <td class="text-center">
    <span class="name">
      <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="col-xs-12 col-sm-8 img-circle img-responsive">
    </span>
  </td>
  <td class="text-center vert-align"><%= full_name applicant %></td>
  <td class="text-center vert-align">
    <span class="label label label-info"><%= applicant.email %></span>
  </td>
  <td class="text-center vert-align">
    <%= applicant.username %>
  </td>
  <td class="text-center vert-align">
    <span class="label label-success"><%= applicant.user_code %></span>
  </td>
  <td class="action text-center vert-align">
  <%= link_to 'مشاهده', show_applicant_path(applicant) %> /
  <%= link_to 'حذف مسئولیت', remove_advisership_path(applicant), method: :delete %>
  </td>
</tr>

app/views/advisers/_tasks_list.html.erb
<br>
مرحله‌<b>اول</b>: اضافه کردن کد کاربری داوطلب
<br>
مرحله‌ی <b>دوم</b>: فعال کردن فرم اطلاعات فیزیکی
<br>
مرحله‌ی <b>سوم</b>: فعال کردن فرم مصاحبه
<br>
مرحله‌ی <b>چهار</b>: فعال کردن آزمون‌ها براساس نتیجه‌ی مصاحبه:
<br>
بعد از ثبت نتایج آزمون مصاحبه، نمره‌هایی در حیطه‌های مختلف برای فرد محاسبه می‌شود که با توجه به آن باید آزمون‌های مختلف را فعال کرد:
<br><br>
اگر نمره‌ی فرد در حیطه‌های انگیزه‌ی پیشرفت، شخصیت و حل مساله کمتر از ۳ بود باید به ترتیب آزمون‌های هرمنس، آیزنگ و هپنر فعال شوند.
<br>
اگر نمره‌ی فرد در حیطه‌ی هوش هیجانی کمتر از ۴ بود باید آزمون بار-آن فعال شود.
<br>
اگر نمره‌ی فرد در حیطه‌ی سازگاری کمتر از ۶ بود باید آزمون بل فعال شود.
<br>
اگر هیچ کدام از مورد بالا برقرار نبود آزمون‌ هالند برای تعیین شغل فعال شود.

app/views/advisers/_tasks_status.html.erb
<%= simple_form_for :status, url: update_status_path(applicant.id), html: {class: 'form-horizontal', role: 'form'} do |f| %>
	<strong>وضعیت کلی متقاضی</strong>
	<%= f.input :status, collection: USER_STATES.each_with_index.map { |content,i| [content,i] }, selected: (applicant.status or 0), input_html: {class: 'form-control col-md-8'}, label: false %>
	<%= f.button :submit , 'اعمال وضعیت',class: 'btn btn-primary' %>
<% end %>

app/views/advisers/detail_about_exam.html.erb
<% if @exam_answer.exam.subject.empty? %>
	<% if @exam_answer.exam.name == 'آزمون بررسی فیزیکی' %>
		<% @exam_answer.answers.includes(:question).each do |answer| %>
			<h3> <%= answer.question.content %> </h3>
			<%= answer.question.choices[answer.choice_index].content %>
		<% end %>
	<% else %>
	<% end %>
<% else %>
	<table class="table">
		<thead>
			<tr>
				<th> حوزه </th>
				<th> نمره </th>
			</tr>
		</thead>
		<tbody>
			<% @exam_answer.exam.subject.each do |key,array| %>
				<tr>
					<td> <%= key %> </td>
					<% if @exam_answer.exam.name == 'مصاحبه' %>
						<td> <%= @exam_answer.get_score array[1..-2].split(',').map { |i| i.to_i - 6 } %> </td>
					<% else %>
						<% arr = array[1..-2].split(',').map { |i| i.to_i - 1 } %>
						<% if @exam_answer.exam.name == 'آزمون رضایت شغلی' %>	
							<td> <%= (@exam_answer.get_score  arr) / arr.size.to_f %> </td>
						<% else %>
							<td> <%= (@exam_answer.get_score  arr) %> </td>
						<% end %>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/advisers/search_applicant.html.erb
<% if @applicant %>
<div class="table-responsive">
	<table class="table table-condensed table-striped  table-hover no-margin borderless">
		<thead>
			<tr>
				<th style="width:10%" class="text-center hidden-phone">تصویر</th>
				<th style="width:20%" class="text-center hidden-phone">نام متقاضی</th>
				<th style="width:10%" class="text-center hidden-phone">پست الکترونیکی</th>
				<th style="width:15%" class="text-center hidden-phone">نام کاربری</th>
				<th style="width:10%" class="text-center hidden-phone">کد کاربری</th>
				<th style="width:15%" class="text-center hidden-phone">عملیات</th>
			</tr>
		</thead>
		<tbody>
			<%= render partial: 'single_applicant', locals: {applicant: @applicant} %>
			<script language='text/javascript'>
				var elements = document.getElementsByClassName("action")
				<% unless @applicant.adviser %>
					elements[elements.length - 1].innerHTML = "<%= escape_javascript(link_to 'اضافه کنید!', add_applicant_path(user_code: @applicant.user_code), method: :post) %>"
				<% else %>
					<% unless current_user == @applicant.adviser %>
						elements[elements.length - 1].innerHTML = '<span class="label label-danger">مشاور دارد</span>'
					<% else %>
						elements[elements.length - 1].innerHTML = '<span class="label label-danger">مشاورش هستید!</span>'
					<% end %>
				<% end %>
			</script>
		</tbody>
	</table>
</div>

<% else %>
متقاضی یافت نشد!
<% end %>

app/views/advisers/show_applicant.html.erb
<div class="row">
  <div class="col-xs-3 col-md-3">
    <%= render partial: 'advisers/applicant_information_for_customer', locals: {applicant: @applicant} %>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-8">
    <div class="tabbable tabs-left">
      <ul class="nav nav-tabs">
        <% class1 = "" %>
        <% class1 = 'active' if params[:tab] == 'tab1' %>
        <% class2 = "" %>
        <% class2 = 'active' if params[:tab] == 'tab9' %>
        <% class3 = "" %>
        <% class3 = 'active' if params[:tab] == 'tab3' %>
        <% class1 = 'active' if (class1 == "" and class2 == "" and class3 == "") %>

        <li class="<%= class1 %>"><a href="#tab1" data-toggle="tab">مراحل راهنمایی متقاضی</a></li>
        <li class="<%= class2 %>"> <a href="#tab9" data-toggle="tab">آزمون‌های متقاضی</a></li>
        <li class="<%= class3 %>"> <a href="#tab3" data-toggle="tab">پیغام وضعیت متقاضی</a></li>
      </ul>

      <div class="tab-content">
        <div class="<%= if (params[:tab] == 'tab1' || !params[:tab])then 'tab-pane active'  else 'tab-pane' end%>" id="tab1">
          <%= render partial: 'advisers/tasks_main', locals: {applicant: @applicant} %>
        </div>
        <div class="<%= if params[:tab] == 'tab9' then 'tab-pane active'  else 'tab-pane' end%>" id="tab9">
          <%= render partial: 'advisers/exams_list', locals: {applicant: @applicant} %>
        </div>
        <div class="<%= if params[:tab] == 'tab3' then 'tab-pane active'  else 'tab-pane' end%>" id="tab3">
          <%= render partial: 'advisers/adviser_message', locals: {applicant: @applicant} %>
        </div>
      </div>
    </div>
  </div>
</div>