config/routes.rb
Phy::Application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#main'

  get '/profile' => 'users#profile'

  get '/search_applicant' => 'advisers#search_applicant'
  post '/add_applicant' => 'advisers#add_applicant'
  delete '/adviser/applicants/:applicant_id' => 'advisers#remove_advisership', as: 'remove_advisership'
  get '/adviser/applicants/:applicant_id' => 'advisers#show_applicant', as: 'show_applicant'
 	post '/adviser/applicants/:applicant_id/update_status' => 'advisers#update_status', as: 'update_status'
 	post '/adviser/applicants/:applicant_id/task_status/:task_status_id/update_status' => 'advisers#update_task_status', as: 'update_task_status'
 	post '/adviser/applicants/:applicant_id/create_exam_answer' => 'advisers#create_exam_answer', as: 'create_exam_answer'	
 	delete '/adviser/applicants/:applicant_id/exam_answers/:exam_answer_id' => 'advisers#delete_exam_answer', as: 'delete_exam_answer'
 	post '/adviser/applicants/:applicant_id/update_message' => 'advisers#update_message', as: 'update_message'

 	get '/applicant/exams/:exam_answer_id' => 'applicants#show_exam', as: 'show_exam'
 	post '/applicant/:exam_answer_id' => 'applicants#submit_answer', as: 'submit_answer'
 	get '/adviser/applicants/:applicant_id/exams/:exam_answer_id' => 'advisers#detail_about_exam', as: 'detail_exam'
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
	before_action :authenticate_user!

	def show_exam
		@exam_answer = current_user.exam_answers.where(id: params[:exam_answer_id]).first
		return redirect_to profile_path, flash: { error: 'آزمون یافت نشد!' } unless @exam_answer
	end

	def submit_answer
		exam_answer = current_user.exam_answers.where(id: params[:exam_answer_id]).first
		return redirect_to profile_path, flash: { error: 'آزمون یافت نشد!' } unless exam_answer
		return redirect_to profile_path, flash: { error: 'قبلا به این آزمون پاسخ داده‌اید' } if exam_answer.status

		if exam_answer.exam.name == 'آزمون هالند'
			handle_holand exam_answer
			return redirect_to profile_path, flash: { success: 'پاسخ‌ها با موفقیت ثبت شدند.' }
		end

		questions = exam_answer.exam.questions
		special = exam_answer.exam.special

		score = 0
		params[:answer].each do |question_index, choice_index|
			questions[question_index.to_i].answers.create user_id: current_user.id, exam_answer_id: exam_answer.id, choice_index: choice_index.to_i
			splitted = questions[question_index.to_i].mask.split('')
			score += splitted[choice_index.to_i].to_i
		end
		exam_answer.update_attributes status: true, score: score
		return redirect_to profile_path, flash: { success: 'پاسخ‌ها با موفقیت ثبت شدند.' }
	end

	private
	def handle_holand exam_answer
		h = {}
		temp = {}
		params[:answer].keys.each do |main_key|
			splitted = main_key.split('-')
			key, q_id, sq_id, ssq_id = splitted[0], splitted[1], splitted[2], splitted[3]
			h[key] ||= {}
			h[key][q_id] ||= {}
			if key == 't1'
				h[key][q_id][sq_id] ||= {}
				h[key][q_id][sq_id][ssq_id] = params[:answer][main_key].to_i
			else 
				h[key][q_id][sq_id] = params[:answer][main_key]
			end
		end

		puts "h: #{h}"
		keys = ['و', 'ا', 'ج', 'م', 'ه', 'ق']
		result = {}
		keys.each_with_index do |key, i|
			score = 0
			h["t1"].each do |main_q_index, sq|
				sq[i.to_s].each do |j, v|
					score += v
				end
			end

			score += h["t2"]["0"][i.to_s].to_i
			score += h["t2"]["1"][i.to_s].to_i
			result[key] = score
		end

		exam_answer.scores = result
		exam_answer.status = true
		exam_answer.save!

		puts "result: #{result}"
	end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/_adviser_message.html.erb
<h3> پیغام مشاور </h3>
<p>
	<span class="label label-info">
	<%= applicant.adviser_message or 'پیغامی وجود ندارد.'%>
	</span>
</p>

app/views/applicants/_exam_list.html.erb
<% if applicant.exam_answers.any? %>
<div class="table-responsive">
  <table class="table table-condensed table-striped  table-hover no-margin borderless">
    <thead>
      <tr>
        <th style="width:30%" class="text-center hidden-phone">وضعیت</th>
        <th style="width:20%" class="text-center hidden-phone">نام آزمون</th>
      </tr>
    </thead>
    <tbody>
      <% applicant.exam_answers.each do |answer| %>
      <tr>
        <td class="text-center">
          <% if answer.status %>
          <span class="label label-success">دادید</span>
          <% else %>
          <span class="label label-danger">ندادید</span> <small><%= link_to 'شرکت کنید', show_exam_path(answer) %> </a></small>
          <% end %>
        </td>
        <td class="text-center">
          <%= answer.exam.name %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
در حال حاضر آزمونی ندارید.
<% end %>

app/views/applicants/_holand.html.erb
<script type="text/javascript">
	function validate_form()
	{
		var radioButtons = $('.question_section2 input[type="radio"]');
		for(i = 0; i < radioButtons.length-1; i += 7) {
			var check = false;
			for(j = 0; j < 7; j++) {
				if(radioButtons[i+j].checked == true)
				{
					check = true;
					break;
				}
				
			}
			if(check)
				continue;

			alert("سوال شماره‌ی "+(Math.ceil(i/7)+1).toString()+"از سوال آخر ( خودسنجی‌ها) خالی است. پرش کنید.");
			return false;
		}
		return true;
	}
</script>



<% HOLAND[:t1].keys.each do |q_index| %>
	<h3> <%= HOLAND[:t1][q_index][:title] %> </h3>
	<% HOLAND[:t1][q_index][:questions].each do |sq_index, q_array| %>
		<div class="question_section">
		<%= f.input "t1-#{q_index}-#{sq_index}", label: "قسمت #{sq_index+1}" do %>
			<% q_array.each_with_index do |q_content,i| %>
				<div class="row">
					<div class="col-md-3">
						<%= q_content %>
					</div>
					<div class="col-md-2">
						<%= f.input "t1-#{q_index}-#{sq_index}-#{i}", as: :boolean, label: false %>
					</div>
				</div>
			<br>
			<% end %>
    	<% end %>
    	</div>
    	<br><br><br><br>
	<% end %>
<% end %>

<h3> <%= HOLAND[:t2][:title] %> </h3>
<% (0..1).each do |q_i| %>
	<div class="question_section2">
		<%= f.input "t2-#{q_i}", label: "قسمت #{q_i+1}" do %>
			<% HOLAND[:t2][q_i].each_with_index do |q_content, i| %>
				<div class="row">
					<div class="col-md-3">
						<%= q_content %>
					</div>
					<div class="col-md-2">
						<%= f.collection_radio_buttons(
				"t2-#{q_i}-#{i}" ,(0..6).to_a.each_with_index.map { |c,index| [index+1,(c+1).to_s]}, :first, :last
				) do |b|
				b.label { b.radio_button + b.text}
			end
			%>
						
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
	<br><br><br><br>
<% end %>

app/views/applicants/_show.html.erb
<div class="row">
	<div class="col-md-4">
		<%= render partial: 'normal_profile_div' %>
	</div>
	<div class="col-md-5">
		<%= render partial: 'applicants/exam_list', locals: {applicant: current_user} %>
	</div>
	<div class="col-md-3">
		<%= render partial: 'applicants/adviser_message', locals: {applicant: current_user} %>
	</div>
</div>

<% exam = current_user.exam_answers.to_a.find { |ea| ea.exam.name == 'آزمون هالند' and ea.status} %>
<% if exam %>
	<% hash = current_user.get_hash exam %>
	<div class="row">
		<h1> نتایج بررسی شغلی </h1>
		<div class="col-md-3">
			<h3> تیپ شخصیتی </h3>
			<p>
				<%= hash[:definition] %>
			</p>
			<p>
				<%= hash[:desc] %>
			</p>
		</div>
		<div class="col-md-3">
			<h3> صفات شخصیتی </h3>
			<p>
				<%= hash[:attributes] %>
			</p>
		</div>
		<div class="col-md-3">
			<h3> شغل‌های پیشنهادی </h3>
			<p>
				<%= hash[:appro_jobs] %>
			</p>
		</div>
	</div>
<% end %>

app/views/applicants/show_exam.html.erb
<% if @exam_answer.status %>
<p>
	قبلا به این آزمون پاسخ داده‌اید!
</p>
<% else %>
<%= simple_form_for :answer, url: submit_answer_path(@exam_answer), html: {class: 'form-horizontal', role: 'form', onsubmit: "return validate_form();"} do |f| %>
<div class="contrainer exam">
	<% if @exam_answer.exam.name == 'آزمون هالند' %>
	<%= render partial: 'holand', locals: {f: f} %>
	<% else %> 
	<script type="text/javascript">
	function validate_form()
	{
		var radioButtons = $('input[type="radio"]');
		for(i = 0; i < radioButtons.length-1; i += <%= @exam_answer.exam.questions.first.choices.size %>) {
			var check = false;
			for(j = 0; j < <%= @exam_answer.exam.questions.first.choices.size %>; j++) {
				if(radioButtons[i+j].checked == true)
				{
					check = true;
					break;
				}
				
			}
			if(check)
				continue;

			alert("سوال شماره‌ی "+(Math.ceil(i/<%=@exam_answer.exam.questions.first.choices.size %>)+1).toString()+"خالی است. پرش کنید.");
			return false;
		}
		return true;
	}
</script>

	<% @exam_answer.exam.questions.each_with_index do |question,index| %>
	<% choices = question.choices %>
	<% if @exam_answer.exam.name == 'آزمون رضایت شغلی' %>
		<% case index %>
			<% when 0 %>
				<h3> شغل شما </h3>
				<br>
			<% when 22 %>
				<h3> مسئول مستقیم </h3>
				<br>
			<% when 36 %>
				<h3> همکار </h3>
				<br>
			<% when 47 %>
				<h3> ارتقا </h3>
				<br>
			<% when 54 %>
				<h3> حقوق و مزایا </h3>
				<br>
			<% when 63 %>
				<h3> شرایط کار در محیط فعلی </h3>
				<br>
		<% end %>
	<% end %>
	<p>
		<fieldset id="question<%=index%>">
			<legend><b><%= index+1 %>. </b><%= question.content%></legend>
			<%= f.collection_radio_buttons(
				"#{index}" ,choices.each_with_index.map { |choice,index| [index,choice.content]}, :first, :last
				) do |b|
				b.label { b.radio_button + b.text}
			end
			%>
		</fieldset>
	</p>
	<br>
	<% end %>
	<% end %>
</div>
<%= f.submit 'ثبت', class: 'btn btn-success' %>
<% end %>
<% end %>